version: "3.7"

services:
  mypgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diego.rugue@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
